FROM flink:1.18.1-scala_2.12

# Install Python and create symlink
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    ln -sf /usr/bin/pip3 /usr/bin/pip

# Install Python dependencies
COPY ../requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Set Python path
ENV PYTHONPATH=/opt/flink/lib/python
