global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'scorer'
    static_configs:
      - targets: ['host.docker.internal:9108']

  - job_name: 'serving'
    static_configs:
      - targets: ['host.docker.internal:8080']
